# This file was generated by GoReleaser. DO NOT EDIT.
cask "gz-git" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "61c27b062ed6ec384b6b631c85295be0377bb395533d20ebdb5f1324beda95f1"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc3c151d395db4c8ec8ccd6744450dc1f5c1ff51267e5e0ca02725daae58a52a"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a174c43fc44934c114c059fac58586b2df7f455ca200fabac7dd88ac3e82dde5"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "36083a8a61e377aef8cf2358a521131244a140b0a008432ad74972f4eeb54e90"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "gz-git"
  desc "Git repository management CLI tool with multi-forge support"
  homepage "https://github.com/gizzahub/gzh-cli-gitforge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gz-git"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gz-git"]
    end
  end

  # No zap stanza required
end
