# This file was generated by GoReleaser. DO NOT EDIT.
cask "gz-git" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "68b43e68466849d56d2b226ff84672b3bb60aa018ca2221f8f5cc73e979cd873"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7869d4c62a77b5b62faaf59941df1e9d248d99dc5bb8f88db5e0d53badbd7402"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b5df582d935305d6a2bf2f73b0981f1c74770412a5050957c10ec807668b2f1"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "be4c822b93b65c7ec739b8850180181d737eb32ac1726a5389079b9031e1b69d"
      url "https://github.com/gizzahub/gzh-cli-gitforge/releases/download/v#{version}/gz-git_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "gz-git"
  desc "Git repository management CLI tool with multi-forge support"
  homepage "https://github.com/gizzahub/gzh-cli-gitforge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gz-git"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gz-git"]
    end
  end

  # No zap stanza required
end
